SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_LIVES = 3

RESPAWN_TIMER = 2
RESPAWN_INVULNERABILITY = 1

SHOT_RADIUS = 5
SHOT_DURATION = 3

EXPLOSION_RADIUS = 1
EXPLOSION_DURATION = 1

PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

TEXT_SIZE = 30
TEXT_COLOR = (255, 255, 255)